# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(407, 305)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.fn = QtWidgets.QLineEdit(Form)
        self.fn.setObjectName("fn")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fn)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.ln = QtWidgets.QLineEdit(Form)
        self.ln.setObjectName("ln")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ln)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.co = QtWidgets.QLineEdit(Form)
        self.co.setObjectName("co")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.co)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.ad = QtWidgets.QLineEdit(Form)
        self.ad.setObjectName("ad")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ad)
        self.an = QtWidgets.QPushButton(Form)
        self.an.setObjectName("an")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.an)
        self.an.clicked.connect(self.adder)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.me = QtWidgets.QLineEdit(Form)
        self.me.setReadOnly(True)
        self.me.setObjectName("me")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.me)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "                        Add details"))
        self.label_2.setText(_translate("Form", "First Name"))
        self.label_3.setText(_translate("Form", "Last Name"))
        self.label_4.setText(_translate("Form", "Contact"))
        self.label_5.setText(_translate("Form", "Address"))
        self.an.setText(_translate("Form", "ADD NOW"))
        self.label_6.setText(_translate("Form", "Message"))

    def adder(self):
        import insert
        a = self.fn.text().capitalize()
        b = self.ln.text().capitalize()
        c = self.co.text()
        d = self.ad.text()
        if a.isalpha() and b.isalpha() and c.isnumeric() and len(c) == 10 and a != '' and c != '':

            self.me.setText(insert.insertinfo(a,b,c,d))
        else:
            self.me.setText('Invalid entries')


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
