# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updation.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 529)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.sc = QtWidgets.QLineEdit(Form)
        self.sc.setObjectName("sc")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sc)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.showdetails)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_6)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.ofn = QtWidgets.QLineEdit(Form)
        self.ofn.setReadOnly(True)
        self.ofn.setObjectName("ofn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ofn)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.oln = QtWidgets.QLineEdit(Form)
        self.oln.setReadOnly(True)
        self.oln.setObjectName("oln")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.oln)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.oco = QtWidgets.QLineEdit(Form)
        self.oco.setReadOnly(True)
        self.oco.setObjectName("oco")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.oco)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.oad = QtWidgets.QLineEdit(Form)
        self.oad.setReadOnly(True)
        self.oad.setObjectName("oad")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.oad)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.nfn = QtWidgets.QLineEdit(Form)
        self.nfn.setObjectName("nfn")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.nfn)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.nln = QtWidgets.QLineEdit(Form)
        self.nln.setObjectName("nln")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.nln)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.nco = QtWidgets.QLineEdit(Form)
        self.nco.setObjectName("nco")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.nco)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.nad = QtWidgets.QLineEdit(Form)
        self.nad.setObjectName("nad")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.nad)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.updatedetails)
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.pushButton_2)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.mess = QtWidgets.QLineEdit(Form)
        self.mess.setReadOnly(True)
        self.mess.setObjectName("mess")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.mess)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Contact"))
        self.pushButton.setText(_translate("Form", "Show Details"))
        self.label_6.setText(_translate("Form", "Original Details"))
        self.label_2.setText(_translate("Form", "First Name"))
        self.label_3.setText(_translate("Form", "Last Name"))
        self.label_4.setText(_translate("Form", "Contact"))
        self.label_5.setText(_translate("Form", "Address"))
        self.label_7.setText(_translate("Form", "New Details"))
        self.label_8.setText(_translate("Form", "First Name"))
        self.label_9.setText(_translate("Form", "Last Name"))
        self.label_10.setText(_translate("Form", "Contact"))
        self.label_11.setText(_translate("Form", "address"))
        self.pushButton_2.setText(_translate("Form", "Update details"))
        self.label_12.setText(_translate("Form", "Message"))

    def showdetails(self):

        x = self.sc.text()
        if x.isnumeric():
            import retrieve
            if retrieve.bycontact(x) == 0:
                self.mess.setText('No entries found')
            else:
                self.ofn.setText(retrieve.bycontact(x)[0])
                self.oln.setText(retrieve.bycontact(x)[1])
                self.oco.setText(retrieve.bycontact(x)[2])
                self.oad.setText(retrieve.bycontact(x)[3])
        else:
            self.mess.setText('Enter valid contact number')

    def updatedetails(self):

        s = self.sc.text()
        w = self.nfn.text().capitalize()
        x = self.nln.text().capitalize()
        y = self.nco.text()
        z = self.nad.text()
        if w.isalpha() and x.isalpha() and y.isnumeric() and len(
                y) == 10 and w != '' and y != '':

            import update
            self.mess.setText(update.bycontact(s, w, x, y, z))

        else:
            self.mess.setText('Enter valid contact number')


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
